# API Keys (örnek; gerçek anahtarlar secrets olarak eklenecek)
OPENAI_API_KEY = "your-openai-key"
GOOGLE_API_KEY = "your-google-key"

# Opsiyonel: diğer ayarlar
EMBEDDING_MODEL = "text-embedding-004"
LLM_MODEL = "gemini-1.5-flash"
WHISPER_MODEL = "whisper-1"
